version: 2.1
orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.12.5
  inline-orb:
    commands:
      my_command:
        steps:
          - run: echo "Hello, world!"
          - run: echo << pipeline.id >>

jobs:
  build_and_test:
    docker:
      - image: cimg/node:20.10.0
    environment:
      CIRCLE_PROJECT_REPONAME: << pipeline.trigger_parameters.github_app.repo_name >>
      PIPELINE_ID: << pipeline.id >>
      PIPELINE_NUMBER: << pipeline.number >>
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - slack/notify:
          channel: C069396MYC9
          event: pass
          template: basic_success_1
      - run: echo "Repo name within config << pipeline.trigger_parameters.github_app.repo_name >>"
      - inline-orb/my_command
 
workflows:
  on_commit:
    jobs:
      - build_and_test:
          context: slack-orb

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"       
          filters:
            branches:
              only:
                - master
    jobs:
      - build_and_test:
          context: slack-orb
      
